### ISSUE TITLE
Consider comparing to `serde` with `envy`

### ISSUE THREAD

**Issue by connec** [tbarusseau/envload#1]
I've used `serde` + [`envy`](https://docs.rs/envy/latest/envy/) in the past to load environment variables into structs. `envy` provides functions to deserialize any type implementing `serde::Deserialize` from the environment (or an iterator of environment variables). It benefits from all serde's built-in attributes and can be used directly with foreign types that implement `Deserialize` without the need for newtype wrappers or custom parsing logic. It also doesn't need to provide its own derive macro.

What does `envload` support (or plan to support) that isn't covered by this combo?

At first glance, the ability to load `Result` fields looks like one feature (`envy` would try to deserialize a `Result` enum, and probably fail). I suppose that could be useful for more precise error handling/reporting (in `envy` you would have to do some newtype w/ custom deserializer shenanigans to get the same effect – though I have never needed it myself).

**Comment by tbarusseau** [comment]
Hi! I didn't know `envy` was a thing, thanks for sharing!

Ideally I'd like `envload` to be a one-stop shop for loading environment, with minimal dependencies. You define your struct, you provide any relevant options (`field_name`, `default_value` for optionals), and then you can just call `Env::load_env()` (or similar - the current syntax is a bit awkward since it uses traits) and get your environment tightly packed in a struct, kinda similar to what `clap` does with its `structopt`/derive functionalities for command line arguments.

Having a way to collect errors (for example all missing env variables) and probably an opinionated way to display these errors would also make it nice to have when building CLI apps.

What do you think?

**Comment by tbarusseau** [comment]
It also appears that `envconfig` is a thing, and it does things in a much better way, for example the API isn't as convoluted.

`envconfig-rs`: https://github.com/greyblake/envconfig-rs
